header:
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
base_url: https://www.funda.nl/en
keep_cols:
  sold_data:
    - date_sold
    - ym_sold
    - year_sold
#    - term_days
  selling_data:
    - url
    - price
    - price_m2
    - price_m2grond
    - status
    - acceptance
    - listed_since
    - house_type
    - building_type
    - year_built
    - building_roofing
    - building_details
    - size
    - living_area
    - property_area
    - balcony_size
    - other_interior_area
    - other_exterior_area
    - exteriors
    - rooms
    - bathroom
    - bedroom
    - toilets
    - stories
    - layout
    - energy_label
    - insulation
    - heating
    - heatedwater
    - heatingCV
    - heatingAge
    - solarpanels
    - heatpump
    - lowenergy
    - street
    - address
    - zip_code
    - city
    - descrip
    - ownership
    - cadastralarea
    - location
    - garden
    - gardensize
    - gardenorientation
    - balcony
    - parking
    - parkingownproperty
    - enclosedparking
    - neighborhood_name
    - latitude
    - longitude
    - monument
    - monumentstatus
    - DIYhome
    - leasehold
    - buurtid
    - photos
    - neighbourhood_price_m2
    - neighbourhood_families
    - sound
    - ppm25
    - no2
css_selector:
  url: "ContentUrl"
  price: 
    - "Id"
    - 
        - "overdracht-huurprijs"
        - "overdracht-vraagprijs"
  price_m2:
     - "Id"
     - "overdracht-vraagprijsperm2"
  status:
    - "Id"
    - "overdracht-status"
  acceptance:
    - "Label"
    - "Aanvaarding"
  listed_since: 
    - "Label"
    - 
        - "Aangeboden sinds"
  house_type: 
    - "Id"
    - "bouw-soortobject"
  building_type: 
    - "Id"
    - "bouw-soortbouw"
  year: 
    - "Label"
    - 
        - "Bouwjaar"
        - "Bouwperiode"
  building_roofing:
    - "Id"
    - "bouw-dak"
  building_details:
    - "Id"
    - "bouw-bijzonderheden"
  size: 
    - "Id"
    - "afmetingen-inhoud"
  living_area: "woonoppervlakte"
  property_area: "PerceelOppervlakteSubTitle" 
  balcony_size: 
    - "Id"
    - "afmetingen-gebruiksoppervlakte-gebouwgebondenbuitenruimte"
  other_interior_area: 
    - "Id"
    - "afmetingen-gebruiksoppervlakte-overigeinpandigeruimte"
  other_exterior_area: 
    - "Label"
    - "Externe bergruimte"
  exteriors: 
    - "Id"
    - "afmetingen-gebruiksoppervlakte-externebergruimte"
  num_of_rooms: "aantalkamers"
  num_of_bathrooms: 
    - "Id"
    - "indeling-totalbathroom"
  num_of_bedrooms: "NumberOfBedrooms"
  stories: 
    - "Id"
    - "indeling-totalstories"
  layout: 
    - "Id"
    - "indeling-generalfacilities"
  energy_label: "EnergyLabel"
  insulation: 
    - "Id"
    - "energie-isolatie"
  heating: 
    - "Id"
    - "energie-verwarming"
  heatedwater:
    - "Id"
    - "energie-warmwater"
  heatingCV:
    - "Id"
    - "energie-cv"
  heatingAge: "cvketel"
  solarpanels: "zonnepanelen"
  heatpump: "warmtepomp"
  lowenergy: "energiezuinig"
  street: "AddressTitle"
  address: "AddressSubTitle"
  zip_code: "postcode"
  city: "plaats"
  descrip: "Aanbiedingstekst"
  ownership: 
    - "Id"
    - "cadastral-ownershipsituation"
  cadastralarea:
    - "Id"
    - "cadastral-area"
  location: 
    - "Id"
    - "buitenruimte-ligging"
  garden: 
    - "Id"
    - "buitenruimte-tuin"
  gardensize:
    - "Id"
    - "buitenruimte-hoofdtuin"
  gardenorientation:
    - "Id"
    - "buitenruimte-liggingtuin"
  balcony:
    - "Id"
    - "buitenruimte-balkonterras"
  parking: 
    - "Label"
    - "Soort parkeergelegenheid"
  parkingownproperty: "parkeergelegenheidopeigenterrein"
  enclosedparking: "parkeergelegenheidopeigenterrein"
  neighborhood_name: "BuurtName"
  latitude: "Latitude"
  longitude: "Longitude"
  monument: "rijksmonument"
  monumentstatus: "monumentalestatus"
  DIYhome: "kluswoning"
  leasehold: "erfpacht"
  buurtid: "BuurtIdentifier"
  photos:
  term: 
  price_sold:
  date_sold:
  neighbourhood_price_m2:
  neighbourhood_families:
  sound:
  ppm25:
  no2: